packages:
  - benchmarks/*/
  - bin
  - packages/*/
catalog:
  '@arktype/attest': ^0.46.0
  '@babel/cli': ^7.25.9
  '@babel/core': ^7.26.0
  '@babel/plugin-transform-export-namespace-from': ^7.25.9
  '@babel/plugin-transform-modules-commonjs': ^7.25.9
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.9
  '@types/node': ^22.9.0
  '@vitest/coverage-v8': 3.1.1
  '@vitest/ui': 3.1.1
  babel-plugin-annotate-pure-calls: ^0.4.0
  fast-check: ^4.1.1
  i18next: ^25.2.1
  madge: ^8.0.0
  typescript: 5.8.3
  vite: ^6.3.5
  vitest: ^3.0.4
